[package]
name = "tudu-server"
version = "0.1.0"
authors = ["mandreyel <mandreyel@protonmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
futures = "0.1.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
diesel = { version = "1.0", features = ["mysql"] }
dotenv = "0.9"
